SINGULARITY_TMPDIR=$(pwd)/tmp
SINGULARITY_CACHEDIR=$(pwd)/.singularity
SINGULARITY_LOCALCACHEDIR=$(pwd)/tmp
TMPDIR=$(pwd)/tmp

mkdir -p $SINGULARITY_TMPDIR
mkdir -p $SINGULARITY_CACHEDIR

echo $SINGULARITY_TMPDIR
echo $SINGULARITY_CACHEDIR

export SINGULARITY_TMPDIR
export SINGULARITY_CACHEDIR
export SINGULARITY_LOCALCACHEDIR
export TMPDIR
